### ISSUE TITLE
How can get items by UpdatedDateUTC

### ISSUE THREAD

**Issue by sandysaille** [freakboy3742/pyxero#186]
I've tried to get all items in Xero, but I cannot filter datetime in timerange by using https://developer.xero.com/documentation/api/items

Scenario:
I would like to get items data in period of Jan 2017 to May 2017. How can I filter in pyxero?

Thanks,
Sandy

**Comment by Munduruca** [comment]
@sandysaille Did you manage to get for instance "xero.journals.all()" from '01/01/2017' forth?
I don't know how to set up this type of parameter...

this way, I'm retrieving just a couple of lines...
journals = xero.journals.all()

Cheers!

**Comment by sandysaille** [comment]
@Munduruca Thanks, anyway I can filter by date time of invoices by using filter.

Thanks again!

**Comment by Munduruca** [comment]
well... apparently I'm missing something. When I try to retrieve "journals" regardless of the filter or page I'm retrieving always the same 100 lines.

If you have an opportunity, have a look here.
https://github.com/freakboy3742/pyxero/issues/190

Thank you for your answer and have an amazing week!

**Comment by Koraki** [comment]
I have just gone through the PyXero SDK as well as re-creating my own requests/oauth 1 mini package to test and believe this is due to the page parameter being passed.

The journals endpoint only accepts the offset parameter.

I have tried to pass this as follows:
![image](https://user-images.githubusercontent.com/37848750/69120855-cca3c300-0aee-11ea-9bb5-9a31481d8552.png)

And can see the params and headers added:
![image](https://user-images.githubusercontent.com/37848750/69120877-d9281b80-0aee-11ea-80c6-2d66b2e98037.png)

But still pyXero doesn't seem to construct the correct endpoint as no matter what offset passed, same resultset. Xero has 288 journals in the dmeo company so shouldn't be seeing the same when offsetting like I have (numerous different offset values)

On the dummy one I recreated I got it to successfully paginate using offset, core of that code is:

`
import requests
from requests_oauthlib import OAuth1
from oauthlib.oauth1 import SIGNATURE_RSA, SIGNATURE_TYPE_AUTH_HEADER

#Define client key
consumer_key = 'my consumer key'

#read rsa_key
with open('<my .pem file>') as keyfile:
    key = keyfile.read()

#create header and make get request in line with guidance 
#from  https://requests-oauthlib.readthedocs.io/en/latest/oauth1_workflow.html

#Create Header
headeroauth = OAuth1(consumer_key,
                    resource_owner_key=consumer_key,
                    signature_method=SIGNATURE_RSA,
                    rsa_key=key,
                    signature_type=SIGNATURE_TYPE_AUTH_HEADER)

#Base Url
url = 'https://api.xero.com/api.xro/2.0/journals'

#Create Headers
headers = {}
headers['Accept'] = 'application/json'
headers['User-Agent'] = 'testPyXeroThing'

#Dict to hold response text
resp = {}

#Test range to paginate using offset
for i in range(0, 5):
    url2 = url + '?offset='+str(i*100)
    print(url2)
    r = requests.get(url2, auth=headeroauth, headers=headers)
    resp[i] = r.text

#write results to file
for t in resp:
    with open('test.txt', 'a+') as f:
        f.write(r.text)

`
