### ISSUE TITLE
Add some caching functionality to minimize the APIs usage 

### ISSUE THREAD

**Issue by housUnus** [freakboy3742/pyxero#349]
Instead of fetching data each time, allow the user to specify how much he wants to keep data in cache, most of the time the data is prefetched even without any change, which consumes the APIs per day and per minute, and also slow down the server response.

**Comment by freakboy3742** [comment]
As the adage says - there's are only 2 hard problems in computer science: caching, naming things, and off by one errors :-)

Adding a caching layer would require a *massive* overhead, and would introduce a whole lot of unpredictable behavior - or, at least, behavior that would need to be clearly documented, and then becomes a source of bugs unto itself.

On that basis, I'm going to close this as WONTFIX. If you have a concrete design *and* a proof-of-concept implementation, I might be convinced to take a look - but my initial impression is that this is an app design issue, not something an API access layer should be managing.

**Comment by housUnus** [comment]
Hi, i don't know if i'm missing something, but i could add some caching functionality using the requests_cache library, the caching will be optional to the users, as an application with many users, we expire the 60calls/m quickly and sometimes the 5000calls/day get expired, so we added a caching of 1 minute, that helped a lot:

from requests_cache import CachedSession
...
def __init__(self):
        self.session = CachedSession(expire_after=self.cache_in)
....
response = getattr(self.session, method)(
                uri,
                data=body,
                headers=headers,
                auth=self.credentials.oauth,
                params=params,
                timeout=timeout,
            )
...
Take a look at the basemanager of my forked package, forget the "#Prevent more than 60 calls per minute logic" block

**Comment by freakboy3742** [comment]
Yes - you're missing something. 

Caching isn't a magic "go faster" machine. It introduces *exceedingly* complex interactions and complications to any code that uses it. It's almost impossible to implement a "universal" caching implementation. 

There's a very good reason that it's the core of the joke I referenced in my original response. Consider the following trivial interaction:

1. Retrieve the value of invoice 1234, get a value of $1000
2. Update invoice 1234 to have a value of $2000.
3. Retrieve invoice 1234

What is the value of invoice 1234? What is the value returned by step 3? 

If you've got no caching, it's 2 read requests and one write request, and the answer is unambiguous. 

If you're caching at the level of *requests*, it's one read request and one write request, and you've got the wrong answer in step 3. 

If you're caching at the level of the PyXero API, you've got a complex implementation so that executing step 2 either busts the cache so that step 3 executes a clean request, or maintains an internal state so that step 3 uses an internal state... but is subject to issues where a separate request has updated invoice 1234 and you're unaware of those changes.

In your *specific* case, request-based caching *may* be viable. If you're not doing writes, then caching reads is a trivial speedup. A generic API layer like PyXero can't make that assumption, because the usage patterns of end users are unknown.

That said, if your proposal is "allow the end user to specify their own session object" - that's a *very* different request, and one that I might be inclined to support - but that isn't "Add caching functionality".
